using Unity.Mathematics;
using UnityEngine;

public class VisualHitboxRenderBehavior : GameplayObjectRenderBehavior<VisualHitbox>
{
    private MeshRenderer meshRenderer;
    [SerializeField] private MeshRenderer bombCrossMeshRenderer;

    private static readonly int SHADER_HITBOXID = Shader.PropertyToID("_HitboxType_Float");
    private static readonly int SHADER_NORMALIZEDPROGRESSID = Shader.PropertyToID("_NormalizedProgress");

    protected override void OnAwake()
    {
        meshRenderer = GetComponent<MeshRenderer>();

        meshRenderer.GetPropertyBlock(propertyBlock);
    }

    protected override void OnRenderEvent()
    {
        GameManager.GameInstance.OnGameSettingsChanged += GameInstance_OnGameSettingsChanged;
        SetPosition();
        float hitboxIDFloat;

        if (AssociatedGameplayObject.HitboxType == HitboxType.A) hitboxIDFloat = 0f;
        else if (AssociatedGameplayObject.HitboxType == HitboxType.B) hitboxIDFloat = 1f;
        else hitboxIDFloat = 2f;

        bombCrossMeshRenderer.gameObject.SetActive(AssociatedGameplayObject.HitboxType == HitboxType.BOMB);

        propertyBlock.SetFloat(SHADER_HITBOXID, hitboxIDFloat);
        propertyBlock.SetFloat(SHADER_NORMALIZEDPROGRESSID, GetNormalizedProgressFloat());
        meshRenderer.SetPropertyBlock(propertyBlock);
        bombCrossMeshRenderer.SetPropertyBlock(propertyBlock);
    }

    private void SetPosition()
    {
        Vector2 screenPoint = MathHelper.GetScreenPointFromNormalizedPointInsideReferenceUI(AssociatedGameplayObject.NormalizedPosition, GameplayManager.GameplayInstance.GameplayRectTransform);

        Vector3 spawnPoint = GameplayManager.GameplayInstance.GameplayCamera.ScreenToWorldPoint(new Vector3(screenPoint.x, screenPoint.y, GameplayManager.k_HITPLANEDEPTH));
        float zTimeDisplacement = (float)((AssociatedGameplayObject.RenderTime - GameplayManager.GameplayInstance.CurrentGameplayTime) * GameManager.GameInstance.GlobalSettings.GameSettings.GameScrollSpeed);

        Vector2 screenSize = MathHelper.GetPixelSizeOfNormalizedSizeVector(AssociatedGameplayObject.NormalizedSize * Vector2.one, GameplayManager.GameplayInstance.GameplayRectTransform);
        Vector3 worldSize = screenSize * GameplayManager.GameplayInstance.WorldToScreenSizeRatioOfPreview * GameManager.aspectRatioConversionScale;

        transform.position = spawnPoint + new Vector3(0f, 0f, zTimeDisplacement);
        transform.localScale = worldSize + new Vector3(0f, 0f, 1f);
    }
    private void GameInstance_OnGameSettingsChanged()
    {
        SetPosition();
    }

    protected override void OnUnrenderEvent()
    {
        GameManager.GameInstance.OnGameSettingsChanged -= GameInstance_OnGameSettingsChanged;
        return;
    }

    private const float k_XSTEPCONSTANT = 0.618033989f; // generated by getting the fractional part of 1 * phi
    private const float k_YSTEPCONSTANT = 0.236067977f; // generated by getting the fractional part of 2 * phi
    protected override void OnUpdateEvent()
    {
        propertyBlock.SetFloat(SHADER_NORMALIZEDPROGRESSID, GetNormalizedProgressFloat());

        meshRenderer.SetPropertyBlock(propertyBlock);
        if (AssociatedGameplayObject.HitboxType == HitboxType.BOMB)
        {
            bombCrossMeshRenderer.SetPropertyBlock(propertyBlock);
        }
    }

    private float GetNormalizedProgressFloat()
    {
        double lookaheadTime = GameManager.GameInstance.GlobalSettings.GameSettings.GameLookaheadTime;
        double progress = (math.max(0d, (GameplayManager.GameplayInstance.CurrentGameplayTime + lookaheadTime - AssociatedGameplayObject.RenderTime) / lookaheadTime));

        // use (25^x - 1) / 24 graph for exponential curve

        return (float)((math.pow(25d, progress) - 1) / 24d);
    }

    protected override void OnDestroy()
    {
        GameManager.GameInstance.OnGameSettingsChanged -= GameInstance_OnGameSettingsChanged;
    }

}
